name: Build SURFBEE_G071, SURFBEEVP_G071

on:
  workflow_dispatch:  # Enables manual triggering
  push:
    branches:
      - surfbee_v1.96
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install ARM SDK
        run: make arm_sdk_install

      - name: Build SURFBEE_G071
        run: make SURFBEE_G071

      - name: Upload Bin File
        uses: actions/upload-artifact@v4
        with:
          name: SURFBEE_G071-bin
          path: obj/*SURFBEE_G071*.bin

      - name: Upload Hex File
        uses: actions/upload-artifact@v4
        with:
          name: SURFBEE_G071-hex
          path: obj/*SURFBEE_G071*.hex
